output_dir: /Users/ely/Documents/Maestria/proyecto_tecnologico/cimat2024-proyecto/Tareas/2024_07_11/torchprotein_output/

dataset:
  class: Solubility
  path: /Users/ely/Documents/Maestria/proyecto_tecnologico/cimat2024-proyecto/Tareas/2024_07_11/
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: "residue"

task:
  class: PropertyPrediction
  model:
    class: ProtBert
    path: /Users/ely/Documents/Maestria/proyecto_tecnologico/cimat2024-proyecto/Tareas/2024_07_11/protbert-model-weights/
    readout: mean
  criterion: ce
  metric: ["acc", "mcc"]
  num_mlp_layer: 2
  num_class: 2
 
eval_metric: accuracy

optimizer:
  class: Adam
  lr: 5.0e-5

fix_encoder: True

engine:
  gpus: [0]
  batch_size: 8

train:
  num_epoch: 50