output_dir: ~/scratch/torchprotein_output/

dataset:
  class: HumanPPI
  path: ~/scratch/protein-datasets/
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: TruncateProtein
        max_length: 550
        random: True
        keys: [ "graph1", "graph2" ]
      - class: ProteinView
        view: "residue"
        keys: [ "graph1", "graph2" ]

test_split: test

task:
  class: InteractionPrediction
  model:
    class: ESM
    path: ~/scratch/esm-model-weights/
    model: ESM-1b
  criterion: ce
  metric: ["acc", "mcc"]
  num_mlp_layer: 2
  num_class: 2

eval_metric: accuracy

optimizer:
  class: Adam
  lr: 2.0e-4

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 2

lr_ratio: 0.1

train:
  num_epoch: 50